### ISSUE TITLE
Initial implementation items

### ISSUE THREAD

**Issue by shgtkshruch** [shgtkshruch/no-js#1]
## TODO
- [ ] `-webkit-line-clamp`
- [ ] `position: sticky`
- [ ] `scroll-behavior: smooth`
- [ ] [CSS Scroll Snap](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap)
- [ ] `loading="lazy"`

## References
- https://calendar.perfplanet.com/2020/html-and-css-techniques-to-reduce-your-javascript/
